name: deploy gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: update sessions in db
        run: npm run update-sessions
        if: false
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: npm (install + build)
        run: npm install && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHTOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
