name: pre-process db

on:
  schedule:
    # min hour day month day-of-week
    # UTC = (LA + 7) = (NY + 4)
    # LA: 17h-0h, 10h,12h,14h,16h
    - cron: "0 0-7 * * *"
    - cron: "0 17,19,21,23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: update sessions in db
        run: npm run update-sessions
        env:
          API_KEY: ${{ secrets.API_KEY }}
